/** Major US metro → primary commercial airport codes for assignment travel. */
const CITY_AIRPORTS: Record<string, string> = {
  portland: 'PDX',
  seattle: 'SEA',
  houston: 'IAH',
  dallas: 'DFW',
  'fort worth': 'DFW',
  austin: 'AUS',
  'san antonio': 'SAT',
  chicago: 'ORD',
  'los angeles': 'LAX',
  'san francisco': 'SFO',
  'san diego': 'SAN',
  'new york': 'JFK',
  brooklyn: 'JFK',
  manhattan: 'LGA',
  boston: 'BOS',
  philadelphia: 'PHL',
  atlanta: 'ATL',
  miami: 'MIA',
  denver: 'DEN',
  phoenix: 'PHX',
  'las vegas': 'LAS',
  minneapolis: 'MSP',
  detroit: 'DTW',
  cleveland: 'CLE',
  columbus: 'CMH',
  cincinnati: 'CVG',
  nashville: 'BNA',
  memphis: 'MEM',
  'new orleans': 'MSY',
  'kansas city': 'MCI',
  'st louis': 'STL',
  'st. louis': 'STL',
  indianapolis: 'IND',
  milwaukee: 'MKE',
  baltimore: 'BWI',
  washington: 'DCA',
  arlington: 'DCA',
  charlotte: 'CLT',
  raleigh: 'RDU',
  orlando: 'MCO',
  tampa: 'TPA',
  jacksonville: 'JAX',
  sacramento: 'SMF',
  oakland: 'OAK',
  'san jose': 'SJC',
  salt: 'SLC',
  'salt lake': 'SLC',
  'salt lake city': 'SLC',
  albuquerque: 'ABQ',
  tucson: 'TUS',
  omaha: 'OMA',
  tulsa: 'TUL',
  'oklahoma city': 'OKC',
  richmond: 'RIC',
  norfolk: 'ORF',
  pittsburgh: 'PIT',
  buffalo: 'BUF',
  rochester: 'ROC',
  albany: 'ALB',
  hartford: 'BDL',
  providence: 'PVD',
  portlandme: 'PWM',
  anchorage: 'ANC',
  honolulu: 'HNL',
};

const STATE_DEFAULT_AIRPORTS: Record<string, string> = {
  AL: 'BHM',
  AK: 'ANC',
  AZ: 'PHX',
  AR: 'LIT',
  CA: 'LAX',
  CO: 'DEN',
  CT: 'BDL',
  DE: 'PHL',
  FL: 'MCO',
  GA: 'ATL',
  HI: 'HNL',
  ID: 'BOI',
  IL: 'ORD',
  IN: 'IND',
  IA: 'DSM',
  KS: 'ICT',
  KY: 'SDF',
  LA: 'MSY',
  ME: 'PWM',
  MD: 'BWI',
  MA: 'BOS',
  MI: 'DTW',
  MN: 'MSP',
  MS: 'JAN',
  MO: 'STL',
  MT: 'BIL',
  NE: 'OMA',
  NV: 'LAS',
  NH: 'MHT',
  NJ: 'EWR',
  NM: 'ABQ',
  NY: 'JFK',
  NC: 'CLT',
  ND: 'FAR',
  OH: 'CMH',
  OK: 'OKC',
  OR: 'PDX',
  PA: 'PHL',
  RI: 'PVD',
  SC: 'CHS',
  SD: 'FSD',
  TN: 'BNA',
  TX: 'DFW',
  UT: 'SLC',
  VT: 'BTV',
  VA: 'RIC',
  WA: 'SEA',
  WV: 'CRW',
  WI: 'MKE',
  WY: 'CYS',
  DC: 'DCA',
};

/** Resolve the nearest major airport code for a US city/state pair. */
export function resolveAirportCode(city: string, state: string): string {
  const normalizedCity = city.trim().toLowerCase();
  const normalizedState = state.trim().toUpperCase();

  const cityMatch = CITY_AIRPORTS[normalizedCity];
  if (cityMatch) {
    return cityMatch;
  }

  for (const [key, code] of Object.entries(CITY_AIRPORTS)) {
    if (normalizedCity.includes(key) || key.includes(normalizedCity)) {
      return code;
    }
  }

  return STATE_DEFAULT_AIRPORTS[normalizedState] ?? 'AUS';
}
